#!/bin/sh

export XDG_SESSION_TYPE=x11
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && sudo exec /etc/vnc/xstartup
[ -r /root/.Xresources ] && sudo xrdb /root/.Xresources
sudo vncconfig -nowin &
sudo dbus-launch -exit-with-session /usr/bin/startplasma-x11
